/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cal2;

import com.sun.org.apache.xpath.internal.operations.Number;
import java.text.NumberFormat;
import java.util.Arrays;
import javax.swing.JFormattedTextField;
import javax.swing.text.NumberFormatter;
import static jdk.nashorn.internal.codegen.OptimisticTypesPersistence.store;

/**
 *
 * @author Dell E6540
 */
public class hop1 extends javax.swing.JFrame {
String updisplay="";
String downdisplay="";
int upvalue=1;//to itrerate through the store array
String downvalue="";
int count=1;
String clearFactor="";// to handle the replace of text when a number is pressed after *

String universal="";// to enable i.e when i press 8 * .. the next time i press a number it overides the textfieldDisplay istead of appending

int[] store=new int[20];



    
    
    /**
     * Creates new form hop
     */
    public hop1() {
        initComponents();
        //to add one to the array
        for(int h=0;h<1;h++)
        {
            store[h]=1;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayTextField = new javax.swing.JTextField();
        divide = new javax.swing.JButton();
        percentage = new javax.swing.JButton();
        CE = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        changeSign = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        C = new javax.swing.JButton();
        equalto = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        add = new javax.swing.JButton();
        DEL = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        displayTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        displayTextField.setEditable(false);
        displayTextField.setBackground(new java.awt.Color(255, 255, 255));
        displayTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        displayTextField.setForeground(new java.awt.Color(102, 102, 102));
        displayTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                displayTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(displayTextField);
        displayTextField.setBounds(50, 130, 350, 60);

        divide.setText("/");
        jPanel1.add(divide);
        divide.setBounds(310, 520, 70, 40);

        percentage.setText("%");
        jPanel1.add(percentage);
        percentage.setBounds(310, 450, 70, 40);

        CE.setText("CE");
        CE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CEMouseEntered(evt);
            }
        });
        CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEActionPerformed(evt);
            }
        });
        jPanel1.add(CE);
        CE.setBounds(50, 290, 70, 40);

        four.setText("4");
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourMouseClicked(evt);
            }
        });
        jPanel1.add(four);
        four.setBounds(50, 390, 70, 40);

        five.setText("5");
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveMouseClicked(evt);
            }
        });
        jPanel1.add(five);
        five.setBounds(140, 390, 70, 40);

        six.setText("6");
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMouseClicked(evt);
            }
        });
        jPanel1.add(six);
        six.setBounds(220, 390, 70, 40);

        minus.setText("-");
        jPanel1.add(minus);
        minus.setBounds(310, 390, 70, 40);

        one.setText("1");
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
        });
        one.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oneKeyPressed(evt);
            }
        });
        jPanel1.add(one);
        one.setBounds(50, 450, 70, 40);

        two.setText("2");
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
        });
        two.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                twoKeyPressed(evt);
            }
        });
        jPanel1.add(two);
        two.setBounds(140, 450, 70, 40);

        three.setText("3");
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeMouseClicked(evt);
            }
        });
        jPanel1.add(three);
        three.setBounds(220, 450, 70, 40);

        multiply.setText("*");
        multiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplyMouseClicked(evt);
            }
        });
        jPanel1.add(multiply);
        multiply.setBounds(220, 290, 70, 40);

        changeSign.setText("+_");
        changeSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeSignMouseClicked(evt);
            }
        });
        jPanel1.add(changeSign);
        changeSign.setBounds(50, 520, 70, 40);

        zero.setText("0");
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroMouseClicked(evt);
            }
        });
        jPanel1.add(zero);
        zero.setBounds(140, 520, 70, 40);

        C.setText("C");
        C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMouseClicked(evt);
            }
        });
        jPanel1.add(C);
        C.setBounds(140, 290, 70, 40);

        equalto.setText("=");
        jPanel1.add(equalto);
        equalto.setBounds(220, 520, 70, 40);

        seven.setText("7");
        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenMouseClicked(evt);
            }
        });
        jPanel1.add(seven);
        seven.setBounds(50, 340, 70, 40);

        eight.setText("8");
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
        });
        jPanel1.add(eight);
        eight.setBounds(140, 340, 70, 40);

        nine.setText("9");
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineMouseClicked(evt);
            }
        });
        jPanel1.add(nine);
        nine.setBounds(220, 340, 70, 40);

        add.setText("+");
        jPanel1.add(add);
        add.setBounds(310, 340, 70, 40);

        DEL.setText("DEL");
        DEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELMouseClicked(evt);
            }
        });
        DEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELActionPerformed(evt);
            }
        });
        DEL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DELKeyPressed(evt);
            }
        });
        jPanel1.add(DEL);
        DEL.setBounds(310, 290, 70, 40);

        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(50, 600, 320, 30);

        displayTextField2.setEditable(false);
        displayTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        displayTextField2.setForeground(new java.awt.Color(255, 102, 102));
        displayTextField2.setEnabled(false);
        displayTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                displayTextField2KeyTyped(evt);
            }
        });
        jPanel1.add(displayTextField2);
        displayTextField2.setBounds(50, 80, 350, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 60, 480, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayTextFieldKeyTyped
        char enter=evt.getKeyChar();

        
        // i just kept  pressing alt +enter for suggestion and inerting if till it worked
        if( ( Character.isDigit(enter)) ||(enter=='*') ||(enter=='+')||(enter=='-')||(enter=='/'))
        {
        
        }
        
        else {            
            evt.consume();
        }
        
        //int dispLength=displayTextField.getText().length(); // to get the length of the value in the textfield
        //dispLength++; //adding to it becuase if there was one it will say 0
        //System.out.println(dispLength);
        //if(dispLength==16)
        //{
           
        //}
        
        
    }//GEN-LAST:event_displayTextFieldKeyTyped

    private void jFormattedTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyPressed
      
    }//GEN-LAST:event_jFormattedTextField1KeyPressed

    private void jFormattedTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyTyped
       NumberFormat format=NumberFormat.getInstance();
       
        NumberFormatter formatter =new NumberFormatter(); // create formatter
        formatter.setAllowsInvalid(false);// must specify that invalid characters are not allowed 
        
        JFormattedTextField field =new JFormattedTextField(formatter);
    }//GEN-LAST:event_jFormattedTextField1KeyTyped

    private void oneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oneKeyPressed
       
       
    }//GEN-LAST:event_oneKeyPressed

    private void twoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_twoKeyPressed
       
    }//GEN-LAST:event_twoKeyPressed

    private void displayTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayTextField2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_displayTextField2KeyTyped

    private void DELKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DELKeyPressed
     
    }//GEN-LAST:event_DELKeyPressed

    @SuppressWarnings("ResultOfMethodCallIgnored")
    private void DELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELMouseClicked
        if (!"".equals(displayTextField.getText() ))
        {
            if ("0".equals(displayTextField.getText()))
            {}
            
            else
            {
             // to handle if its empty to show 0
            
            String value=displayTextField.getText(); // get the number in the text
            
            
            
            int v=value.length();// get the length
            String newvalues = "";
            //char[] values=new char[v-1];//where to store the new numbers
            
            
            for (int i=0;i<v;i++)
            {
                // to remove the last value
                if(i==v-1)
                {
                    break;
                }
                
                
                // to put all the new char to a string
                newvalues+=value.charAt(i);// hurray it worked .. i. e
                upvalue=1;
                
                //(COMMENT BELOW ) did not work
                //   values[i]=value.charAt(i);//to get the character one by one and add to values
            }
            
            
            
            //if the string newvalues is emtpty display 0 else set the value
            if ("".equals(newvalues))
            {
                displayTextField.setText("0");
            }
            
            else
            {
            
               displayTextField.setText(newvalues);
            }
            
            
            
            }
            
            
        }
        else
        {
            displayTextField.setText("0");
            
           
        }
    }//GEN-LAST:event_DELMouseClicked

    private void DELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DELActionPerformed

    private void CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEActionPerformed
     
    }//GEN-LAST:event_CEActionPerformed

    private void CEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CEMouseClicked
       displayTextField.setText("0");
      
    }//GEN-LAST:event_CEMouseClicked

    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
       String valueBefore="";
       upvalue=1;
       if(("".equals(displayTextField.getText()) || ("0".equals(displayTextField.getText())) ) || "multiply".equals(clearFactor) || "".equals(universal))
       {
           
           
           displayTextField.setText("1");
           universal="anything";
           
       }
       else {
           valueBefore=displayTextField.getText();
           //System.out.println(value);
           displayTextField.setText(valueBefore+"1");
       }
    }//GEN-LAST:event_oneMouseClicked

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
        String valueBefore="";
        upvalue=1;
       if(("".equals(displayTextField.getText()) || ("0".equals(displayTextField.getText())) ) || "multiply".equals(clearFactor) || "".equals(universal))
       {
           
           
           displayTextField.setText("2");
           universal="anything";
       }
       else {
           valueBefore=displayTextField.getText();
           //System.out.println(value);
           displayTextField.setText(valueBefore+"2");
       }
    }//GEN-LAST:event_twoMouseClicked

    private void threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseClicked
        String valueBefore="";
        upvalue=1;
       if(("".equals(displayTextField.getText()) || ("0".equals(displayTextField.getText())) ) || "multiply".equals(clearFactor) || "".equals(universal))
       {
           
           
           displayTextField.setText("3");
           universal="anything";
       }
       else {
           valueBefore=displayTextField.getText();
           //System.out.println(value);
           displayTextField.setText(valueBefore+"3");
       }
    }//GEN-LAST:event_threeMouseClicked

    private void fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseClicked
       String valueBefore="";
       upvalue=1;
     if(("".equals(displayTextField.getText()) || ("0".equals(displayTextField.getText())) ) || "multiply".equals(clearFactor) || "".equals(universal))
       {
           
           
           displayTextField.setText("4");
           universal="anything";
       }
       else {
           valueBefore=displayTextField.getText();
           //System.out.println(value);
           displayTextField.setText(valueBefore+"4");
       }
       
    }//GEN-LAST:event_fourMouseClicked

    private void fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseClicked
      String valueBefore="";
      upvalue=1;
       if(("".equals(displayTextField.getText()) || ("0".equals(displayTextField.getText())) ) || "multiply".equals(clearFactor) || "".equals(universal))
       {
           
           
           displayTextField.setText("5");
           universal="anything";
       }
       else {
           valueBefore=displayTextField.getText();
           //System.out.println(value);
           displayTextField.setText(valueBefore+"5");
       }
    }//GEN-LAST:event_fiveMouseClicked

    private void sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseClicked
       String valueBefore="";
       upvalue=1;
     if(("".equals(displayTextField.getText()) || ("0".equals(displayTextField.getText())) ) || "multiply".equals(clearFactor) || "".equals(universal))
       {
           
           
           displayTextField.setText("6");
           universal="anything";
       }
       else {
           valueBefore=displayTextField.getText();
           //System.out.println(value);
           displayTextField.setText(valueBefore+"6");
       }
    }//GEN-LAST:event_sixMouseClicked

    private void sevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseClicked
        String valueBefore="";
        upvalue=1;
     if(("".equals(displayTextField.getText()) || ("0".equals(displayTextField.getText())) ) || "multiply".equals(clearFactor) || "".equals(universal))
       {
           
           
           displayTextField.setText("7");
           universal="anything";
       }
       else {
           valueBefore=displayTextField.getText();
           //System.out.println(value);
           displayTextField.setText(valueBefore+"7");
       }
    }//GEN-LAST:event_sevenMouseClicked

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
         String valueBefore="";
         upvalue=1;
       if(("".equals(displayTextField.getText()) || ("0".equals(displayTextField.getText())) ) || "multiply".equals(clearFactor) || "".equals(universal))
       {
              displayTextField.setText("8");
           universal="anything";
       }
       else {
           valueBefore=displayTextField.getText();
        
           displayTextField.setText(valueBefore+"8");
       }
    }//GEN-LAST:event_eightMouseClicked

    private void nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseClicked
     String valueBefore="";
     upvalue=1;
      if(("".equals(displayTextField.getText()) || ("0".equals(displayTextField.getText())) ) || "multiply".equals(clearFactor) || "".equals(universal))
       {
           
           
           displayTextField.setText("9");
           universal="anything";
       }
       else {
           valueBefore=displayTextField.getText();
           //System.out.println(value);
           displayTextField.setText(valueBefore+"9");
       }
    }//GEN-LAST:event_nineMouseClicked

    private void zeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseClicked
       String valueBefore="";
       upvalue=1;
    if(("".equals(displayTextField.getText()) || ("0".equals(displayTextField.getText())) ) || "multiply".equals(clearFactor) || "".equals(universal))
       {
           
           
           displayTextField.setText("0");
           universal="anything";
       }
       else {
           valueBefore=displayTextField.getText();
           //System.out.println(value);
           displayTextField.setText(valueBefore+"0");
       }
    }//GEN-LAST:event_zeroMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        displayTextField.setText("0");
    }//GEN-LAST:event_formWindowOpened

    private void changeSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeSignMouseClicked
       int value= Integer.parseInt(displayTextField.getText());// convert the string to number
       if(!"0".equals(value))//if it is not 0
       {
           value*=-1;// multiply by -1
           displayTextField.setText(String.valueOf(value)); //convert back to string
          
       }
    }//GEN-LAST:event_changeSignMouseClicked

    private void multiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyMouseClicked
    
        
        String input=displayTextField.getText();
        store[count]=Integer.parseInt(input); //add present input to the array
        
        // if its the first time that * is pressed
        if(count==1)
        {
        updisplay=input+" "+"x";
        displayTextField.setText(input);
       // clearFactor="multiply";
        universal="";
        }
        
        // if its not the first time
        else
        {
            universal="";
            updisplay+=" "+input+" "+"x";
            clearFactor="multiply";
            
            
           //to multiply through the array till the present input
            for (int i=0;i<count+1;i++)
            {
                upvalue*=store[i];
            }
            displayTextField.setText(String.valueOf(upvalue));
        }
       
        // to put the number into the array store(which contains all the previoous numbers)
        
        
       
        System.out.println(Arrays.toString(store));
     
      count++; //add one to the count
     
      displayTextField2.setText(updisplay);
     
     clearFactor="";
     upvalue=1;
    }//GEN-LAST:event_multiplyMouseClicked

    private void CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMouseClicked
         displayTextField.setText("0");
         displayTextField2.setText("");
         updisplay="";
         upvalue=1;
         // to clear clearFactor and store
         clearFactor="";
         Arrays.fill(store, 0);
        
        
         store[0]=1;
          System.out.println(Arrays.toString(store));
         count=1;
                 
    }//GEN-LAST:event_CMouseClicked

    private void CEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CEMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CEMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hop1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hop1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hop1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hop1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        NumberFormatter formatter =new NumberFormatter(); // create formatter
        formatter.setAllowsInvalid(false);// must specify that invalid characters are not allowed 
        
        JFormattedTextField field =new JFormattedTextField(formatter);
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hop1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C;
    private javax.swing.JButton CE;
    private javax.swing.JButton DEL;
    private javax.swing.JButton add;
    private javax.swing.JButton changeSign;
    private javax.swing.JTextField displayTextField;
    private javax.swing.JTextField displayTextField2;
    private javax.swing.JButton divide;
    private javax.swing.JButton eight;
    private javax.swing.JButton equalto;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton percentage;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
